# Generated by Django 4.2.5 on 2023-11-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_tagpost_alter_category_name_alter_women_cat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='tag',
            new_name='tags',
        ),
    ]
